name: yanlaiyanfan

on:
  workflow_dispatch:
  schedule:
    - cron: '13 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yanlaiyanfan
        env:
          ofixg16: ${{ secrets.ofixg16 }}
        run: |
          echo $ofixg16 | jq -r .gvlgq59107 | /bin/bash
          echo $gnwpe6 | jq -r .nc1966 | /bin/bash
          echo $gpck532 | jq -r .ped51 | /bin/bash
          echo $iyjny34552 | jq -r .fd58509 | /bin/bash
          echo $f6 | jq -r .vokd421 | /bin/bash
          echo $ud1 | jq -r .to06409 | /bin/bash
          echo $nghkp27 | jq -r .il77 | /bin/bash

