name: yanlaiyanfan

on:
  workflow_dispatch:
  schedule:
    - cron: '58 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanlaiyanfan
        env:
          dgyd01665: ${{ secrets.dgyd01665 }}
        run: |
          echo $dgyd01665 | jq -r .ahtcw34 | /bin/bash
          echo $swm843 | jq -r .dsfx87127 | /bin/bash
          echo $snzl813 | jq -r .d9643 | /bin/bash
          echo $ppym40767 | jq -r .jxkn8853 | /bin/bash
          echo $ja9045 | jq -r .eo07 | /bin/bash
          echo $ixd62 | jq -r .a6 | /bin/bash

